import { Department, Doctor } from '../types';

export const INITIAL_DEPARTMENTS: Department[] = [
  {
    id: 'dept-cardio',
    name: 'Cardiology & Cardiothoracic Surgery',
    code: 'CARDIO',
    description: 'Premier cardiovascular care, primary coronary angioplasty, electrophysiology, bypass surgery (CABG), and pediatric heart surgery.',
    iconName: 'HeartPulse',
    headDoctor: 'Dr. Rajesh Sundaram, MBBS, MD, DM (Cardiology), FACC',
    services: ['2D/3D Echocardiogram', 'Coronary Angiography & Stenting', 'TAVR & Mitral Valve Repair', 'Electrophysiology Study & Pacemaker', 'Cardiac Rehab'],
    roomNumber: 'Dhanvantari Wing - 3rd Floor, Suite 302',
    phone: '+91 (080) 4122-0101',
    image: 'https://images.unsplash.com/photo-1628348068343-c6a848d2b6dd?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'dept-neuro',
    name: 'Neurosciences & Stroke Unit',
    code: 'NEURO',
    description: 'Advanced neuro-navigation surgery, acute ischemic stroke thrombectomy unit, spine instrumentation, and epilepsy monitoring.',
    iconName: 'Brain',
    headDoctor: 'Dr. Ananya Roy, MBBS, MS, MCh (Neurosurgery), AIIMS',
    services: ['3T MRI & Neuro Angiography', 'Endoscopic Brain Surgery', 'Deep Brain Stimulation (DBS)', 'Complex Spinal Fusion', 'Stroke Thrombolysis ICU'],
    roomNumber: 'Charaka Tower - 4th Floor, Suite 410',
    phone: '+91 (080) 4122-0102',
    image: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'dept-ortho',
    name: 'Orthopedics & Robotic Joint Replacement',
    code: 'ORTHO',
    description: 'Robotic total knee and hip arthroplasty, sports arthroscopy, pediatric orthopedics, and 24/7 polytrauma reconstruction center.',
    iconName: 'Bone',
    headDoctor: 'Dr. Vikramaditya Reddy, MBBS, MS (Ortho), DNB, FRCS',
    services: ['Robotic NAVIO Knee Replacement', 'Arthroscopic ACL/Meniscus Repair', 'Complex Pelvic Trauma Care', 'Minimally Invasive Spine Surgery', 'Physiotherapy & Rehab'],
    roomNumber: 'Sushruta Pavilion - 1st Floor, Room 108',
    phone: '+91 (080) 4122-0103',
    image: 'https://images.unsplash.com/photo-1530497610245-94d3c16cda28?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'dept-pedia',
    name: 'Pediatrics & Neonatal ICU (NICU Level IV)',
    code: 'PEDIA',
    description: 'Round-the-clock neonatal critical care, universal infant immunization, pediatric cardiology, and developmental pediatrics.',
    iconName: 'Baby',
    headDoctor: 'Dr. Meenakshi Venkataraman, MBBS, MD (Pediatrics), DCH',
    services: ['Level-IV Tertiary NICU & PICU', 'Pediatric Vaccination & Well Baby Clinic', 'Pediatric Nephrology & Pulmonology', 'Childhood Allergy Testing', 'Newborn Screening'],
    roomNumber: 'Vatsalya Block - 2nd Floor, Room 205',
    phone: '+91 (080) 4122-0104',
    image: 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'dept-onco',
    name: 'Comprehensive Cancer Care & Bone Marrow Transplant',
    code: 'ONCO',
    description: 'State-of-the-art medical, surgical, and radiation oncology with TrueBeam linear accelerators and day-care chemotherapy lounge.',
    iconName: 'ShieldAlert',
    headDoctor: 'Dr. Alok Verma, MBBS, MD, DM (Medical Oncology), Tata Memorial Alumni',
    services: ['Stereotactic Radiosurgery (SRS/SRT)', 'Targeted Immunotherapy & Chemotherapy', 'Organ Preservation Cancer Surgery', 'Bone Marrow Transplant (BMT)', 'Pain & Palliative Clinic'],
    roomNumber: 'Arogya Center - Wing C',
    phone: '+91 (080) 4122-0105',
    image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'dept-genmed',
    name: 'Internal Medicine, Diabetology & Lifestyle Clinic',
    code: 'GENMED',
    description: 'Specialized management of Type 2 Diabetes, hypertension, metabolic syndrome, monsoon fevers (Dengue, Malaria), and preventive health checks.',
    iconName: 'Stethoscope',
    headDoctor: 'Dr. Suresh Kumar Menon, MBBS, MD (General Medicine), FICP',
    services: ['Master Executive Health Checkups', 'Comprehensive Diabetes & Foot Care', 'Geriatric & Multi-morbidity Clinic', 'Tropical Infectious Diseases Management', 'Thyroid & Endocrine Clinics'],
    roomNumber: 'Main OPD Block - Ground Floor, Room 101',
    phone: '+91 (080) 4122-0106',
    image: 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'dept-gastro',
    name: 'Gastroenterology, Hepatology & GI Surgery',
    code: 'GASTRO',
    description: 'Advanced therapeutic endoscopy, ERCP, liver disease management, fatty liver care, and laparoscopic gastrointestinal surgery.',
    iconName: 'Activity',
    headDoctor: 'Dr. Pooja Sharma, MBBS, MD, DM (Gastroenterology)',
    services: ['Video Upper GI Endoscopy & Colonoscopy', 'ERCP for Biliary Stones', 'Capsule Endoscopy', 'Fatty Liver & Cirrhosis Clinic', 'Laparoscopic Gallbladder Surgery'],
    roomNumber: 'Dhanvantari Wing - 2nd Floor, Room 212',
    phone: '+91 (080) 4122-0107',
    image: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'dept-ayur',
    name: 'Ayush & Integrative Holistic Medicine',
    code: 'AYUSH',
    description: 'Evidence-based integrative care combining NABH-accredited modern clinical medicine with authentic Ayurveda, Yoga therapy, and dietetics.',
    iconName: 'Sparkles',
    headDoctor: 'Dr. Padmanabhan Iyer, BAMS, MD (Ayur), PhD (Integrative Med)',
    services: ['Panchakarma Therapies & Detox', 'Therapeutic Yoga & Pranayama', 'Lifestyle & Herbal Medicine Guidance', 'Post-Op Integrative Recovery', 'Stress & Insomnia Rejuvenation'],
    roomNumber: 'Sanjeevani Wellness Wing - Ground Floor',
    phone: '+91 (080) 4122-0108',
    image: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=800&q=80'
  }
];

export const INITIAL_DOCTORS: Doctor[] = [
  {
    id: 'doc-rajesh-sundaram',
    name: 'Dr. Rajesh Sundaram',
    title: 'Senior Consultant & Director of Interventional Cardiology',
    specialty: 'Cardiologist',
    departmentId: 'dept-cardio',
    departmentName: 'Cardiology & Cardiothoracic Surgery',
    qualifications: 'MBBS, MD (Medicine), DM (Cardiology), FACC (USA), AIIMS New Delhi',
    experienceYears: 22,
    consultationFee: 1200, // in INR (₹)
    rating: 4.96,
    reviewCount: 480,
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
    availableSlots: ['09:30 AM', '11:00 AM', '12:30 PM', '02:30 PM', '04:00 PM', '05:30 PM'],
    bio: 'Recognized as one of South Asia’s leading cardiologists with over 6,000 successful coronary interventions, pioneering radial artery angioplasty and complex bifurcation stenting.',
    avatar: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=400&q=80',
    phone: '+91 (080) 4122-4411',
    email: 'r.sundaram@carepulse.hospital',
    status: 'active',
    roomNumber: 'Cardio Suite 302'
  },
  {
    id: 'doc-ananya-roy',
    name: 'Dr. Ananya Roy',
    title: 'Chief Neurosurgeon & Head of Stroke Intervention',
    specialty: 'Neurosurgeon',
    departmentId: 'dept-neuro',
    departmentName: 'Neurosciences & Stroke Unit',
    qualifications: 'MBBS, MS (General Surgery), MCh (Neurosurgery - AIIMS), Fellowship (Oxford)',
    experienceYears: 18,
    consultationFee: 1500,
    rating: 4.94,
    reviewCount: 395,
    availableDays: ['Monday', 'Wednesday', 'Friday', 'Saturday'],
    availableSlots: ['10:00 AM', '11:30 AM', '02:00 PM', '04:00 PM'],
    bio: 'Specialist in minimally invasive keyhole neurosurgery, brain aneurysm coiling, microvascular decompression for trigeminal neuralgia, and awake craniotomies.',
    avatar: 'https://images.unsplash.com/photo-1594824813583-718224534789?auto=format&fit=crop&w=400&q=80',
    phone: '+91 (080) 4122-4412',
    email: 'a.roy@carepulse.hospital',
    status: 'active',
    roomNumber: 'Neuro Suite 410'
  },
  {
    id: 'doc-vikramaditya-reddy',
    name: 'Dr. Vikramaditya Reddy',
    title: 'Director of Robotic Joint Reconstruction & Sports Medicine',
    specialty: 'Orthopedic Surgeon',
    departmentId: 'dept-ortho',
    departmentName: 'Orthopedics & Robotic Joint Replacement',
    qualifications: 'MBBS, MS (Ortho - CMC Vellore), DNB, MCh (Ortho - UK), Fellowship in Robotic Arthroplasty (Germany)',
    experienceYears: 20,
    consultationFee: 1100,
    rating: 4.92,
    reviewCount: 420,
    availableDays: ['Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    availableSlots: ['09:00 AM', '10:30 AM', '01:30 PM', '03:00 PM', '05:00 PM'],
    bio: 'Pioneer of robotic total knee replacement and complex revision hip surgeries, with extensive experience in sports injuries and ACL reconstructions for professional athletes.',
    avatar: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&w=400&q=80',
    phone: '+91 (080) 4122-4413',
    email: 'v.reddy@carepulse.hospital',
    status: 'active',
    roomNumber: 'Ortho Pavilion 108'
  },
  {
    id: 'doc-meenakshi-v',
    name: 'Dr. Meenakshi Venkataraman',
    title: 'Senior Consultant Pediatrician & Neonatologist',
    specialty: 'Pediatrician',
    departmentId: 'dept-pedia',
    departmentName: 'Pediatrics & Neonatal ICU (NICU Level IV)',
    qualifications: 'MBBS, MD (Pediatrics - JIPMER), DCH (London), Fellowship in Neonatal Intensive Care',
    experienceYears: 16,
    consultationFee: 900,
    rating: 4.98,
    reviewCount: 512,
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
    availableSlots: ['09:00 AM', '10:00 AM', '11:30 AM', '03:00 PM', '04:30 PM'],
    bio: 'Known for her warm and patient demeanor with infants and children. Expert in high-risk premature baby care, growth monitoring, and childhood immunization schedules.',
    avatar: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=400&q=80',
    phone: '+91 (080) 4122-4414',
    email: 'm.venkat@carepulse.hospital',
    status: 'active',
    roomNumber: 'Vatsalya Block 205'
  },
  {
    id: 'doc-alok-verma',
    name: 'Dr. Alok Verma',
    title: 'Chief Medical Oncologist & Stem Cell Specialist',
    specialty: 'Oncologist',
    departmentId: 'dept-onco',
    departmentName: 'Comprehensive Cancer Care & Bone Marrow Transplant',
    qualifications: 'MBBS, MD, DM (Medical Oncology - Tata Memorial Centre, Mumbai), ESMO Certified',
    experienceYears: 19,
    consultationFee: 1400,
    rating: 4.95,
    reviewCount: 330,
    availableDays: ['Monday', 'Tuesday', 'Thursday', 'Friday'],
    availableSlots: ['10:00 AM', '11:30 AM', '02:00 PM', '03:30 PM'],
    bio: 'Dedicated to precision oncology, next-generation sequencing genomic therapies, cancer immunotherapy, and compassionate palliative support.',
    avatar: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&w=400&q=80',
    phone: '+91 (080) 4122-4415',
    email: 'a.verma@carepulse.hospital',
    status: 'active',
    roomNumber: 'Arogya Center 12'
  },
  {
    id: 'doc-suresh-menon',
    name: 'Dr. Suresh Kumar Menon',
    title: 'Chief Physician, Internal Medicine & Diabetology',
    specialty: 'General Physician',
    departmentId: 'dept-genmed',
    departmentName: 'Internal Medicine, Diabetology & Lifestyle Clinic',
    qualifications: 'MBBS, MD (General Medicine - Madras Medical College), FICP, Post-Grad Diabetology (Boston)',
    experienceYears: 24,
    consultationFee: 800,
    rating: 4.93,
    reviewCount: 680,
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    availableSlots: ['08:30 AM', '09:30 AM', '10:30 AM', '11:30 AM', '04:00 PM', '05:30 PM'],
    bio: 'Expert in long-term glycemic control, reversing metabolic syndrome, hypertension control, fever triage, and holistic adult medicine.',
    avatar: 'https://images.unsplash.com/photo-1582750433449-648ed127bb54?auto=format&fit=crop&w=400&q=80',
    phone: '+91 (080) 4122-4416',
    email: 's.menon@carepulse.hospital',
    status: 'active',
    roomNumber: 'Main OPD 101'
  },
  {
    id: 'doc-pooja-sharma',
    name: 'Dr. Pooja Sharma',
    title: 'Consultant Medical Gastroenterologist & Hepatologist',
    specialty: 'Gastroenterologist',
    departmentId: 'dept-gastro',
    departmentName: 'Gastroenterology, Hepatology & GI Surgery',
    qualifications: 'MBBS, MD (Medicine), DM (Gastroenterology - SGPGI Lucknow), FASGE',
    experienceYears: 13,
    consultationFee: 1000,
    rating: 4.9,
    reviewCount: 310,
    availableDays: ['Monday', 'Wednesday', 'Thursday', 'Friday'],
    availableSlots: ['09:30 AM', '11:00 AM', '02:30 PM', '04:00 PM'],
    bio: 'Specialist in luminal gastrointestinal disorders, IBS, inflammatory bowel disease (IBD), fatty liver disease, and advanced ERCP procedures.',
    avatar: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=400&q=80',
    phone: '+91 (080) 4122-4417',
    email: 'p.sharma@carepulse.hospital',
    status: 'active',
    roomNumber: 'Dhanvantari Wing 212'
  },
  {
    id: 'doc-padmanabhan-iyer',
    name: 'Dr. Padmanabhan Iyer',
    title: 'Director of Ayush & Holistic Integrative Healing',
    specialty: 'Ayush & Integrative Physician',
    departmentId: 'dept-ayur',
    departmentName: 'Ayush & Integrative Holistic Medicine',
    qualifications: 'BAMS (Kerala Ayurveda Academy), MD (Ayurveda), PhD (Integrative Medicine - NIMHANS)',
    experienceYears: 21,
    consultationFee: 750,
    rating: 4.97,
    reviewCount: 450,
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Saturday'],
    availableSlots: ['09:00 AM', '10:30 AM', '02:00 PM', '03:30 PM', '05:00 PM'],
    bio: 'Bridging ancient classical Ayurvedic science with modern evidence-based clinical diagnostics for chronic arthritis, metabolic health, gut cleansing, and stress recovery.',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
    phone: '+91 (080) 4122-4418',
    email: 'p.iyer@carepulse.hospital',
    status: 'active',
    roomNumber: 'Sanjeevani Wellness Wing 01'
  }
];
